### PR TITLE
Enable Tcl track on website

### PR DESCRIPTION
**Pull request by sshine**
By setting

    "active": true

in config.json, this enables the track on Exercism.io.

@glennj: We can keep this PR hanging until we've merged the exercises you implemented.

### CODE REVIEW

**Comment by sshine** [comment]
@ihid: Since disabling "WIP bot", it seems that I'm unable to use the alternative "Draft PRs" either.

Have we gone from 2 alternatives to 0?

**Comment by iHiD** [comment]
> Since disabling "WIP bot", it seems that I'm unable to use the alternative "Draft PRs" either.

In what way can you not use them?

**Comment by sshine** [comment]
> Since disabling "WIP bot", it seems that I'm unable to use the alternative
> "Draft PRs" either.
>
> In what way can you not use them?
>
In the way that neither present themselves as options, which apparently led
you to merge the PR when the intent of the question was to avoid the PR to
be merged before we're ready. :-D

I understand you disabled WIP bot a while ago, but I couldn't make this a
draft PR.

>

**Comment by iHiD** [comment]
Did you notice this dropdown?

Screenshot 2020-01-06 at 15 02 04

**Pull request merged**
