### PR TITLE
alphametics: make the "big" test optional to speed up CI

### PR DESCRIPTION
**Pull request by glennj**
This implementation of alphametics isn't blazing fast. The last test case takes about 20 seconds to calculate.

Making this case optional will speed up CI for all commits to master.

### CODE REVIEW

**Comment by glennj** [comment]
@exercism/reviewers Can I get some eyes on this PR please?

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
Looks good, but my approval doesn't count. ;)

**Review by ekingery — APPROVED** [review]

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
You get all the checks, non that count 🔢

**Comment by glennj** [comment]
It's the @exercism/maintainers-admin team that I need now, right?

**Comment by iHiD** [comment]
This does work quite well, in that I can just merge without checking on the basis of the @reviewers actually checking it.

But we'll get reviewers write-permissions this week :)

**Comment by glennj** [comment]
Thanks, the tests now run in 16 seconds, down from 43 in the last commit to master.

**Comment by iHiD** [comment]
Nice pragmatism 🙂

**Pull request merged**
