### PR TITLE
Bank-account: create exercise

### PR DESCRIPTION
**Pull request by glennj**
It took me a while to decide which implementation I wanted to go with. I went with a simple class-based one where the implementation has no special thread-based locking at all: the message-passing style of inter-thread communication (using the Tcl event loop) takes care of all the locking for us.

My alternate  implementation uses thread-shared-variables to maintain the bank account state. This code specifically uses thread locks to maintain synchronization. I didn't want to throw it away so I stashed it in the .meta subdirectory.

### CODE REVIEW

**Comment by glennj** [comment]
@sshine this is ready for review now.

**Comment by sshine** [comment]
Excellent, I'll look at it in my lunch break.

**Comment by glennj** [comment]
I don't understand your comment. In both test suites, the  bank-account-15 test validates that operations on the account work concurrently. The difference between the two .test files is the way the account is created and invoked as a command.

**Comment by glennj** [comment]
@sshine Hi Simon. Are you OK with this getting merged? I'm uncertain about how we left this PR.

**Pull request merged**
