### PR TITLE
Matrix: create exercise

### PR DESCRIPTION
**Pull request by glennj**
[The README](https://github.com/glennj/tcl/blob/port/matrix/exercises/matrix/README.md) rendered.

problem spec [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json)

### CODE REVIEW

**Comment by glennj** [comment]
> Excellent structure!

Thank you.

> Why is `Transpose` uppercased when `row` and `column` are lowercased?

Methods starting with a lower-case letter are automatically exported (https://tcl.tk/man/tcl8.6/TclCmd/define.htm#M12). So `Transpose` is private.

> I happened to take part in a discussion of this exercise in [exercism/ruby#962](https://github.com/exercism/ruby/issues/962) in which my main point was that [constructors shouldn't do real work](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/). 

I see your point. I'll refactor a bit.

> Also, notice that matrix tests were updated in [exercism/problem-specifications#1576](https://github.com/exercism/problem-specifications/pull/1576) bumping it to 1.2.0.

And I'll update the tests.

I appreciate the feedback.

**Comment by glennj** [comment]
I noticed the "can extract column from non-square matrix with no corresponding row" canonical test has some extra whitespace around the newline, so I added a couple of tests specifically for that.

**Comment by sshine** [comment]
Nice. I see that you've changed the exercise to lazily parse columns/rows. This was @yyyc514's idea.

The structure even allows for non-OO solutions, which is great. I think, however, this means that if we don't place it before an exercise that contains OO-related stub code, we won't see a lot of OO solutions to this exercise.

Should we wait a little for canonical version 1.3.0 in exercism/problem-specifications#1577?

**Comment by yawpitch** [comment]
Version 1.3.0 is now merged.

**Comment by glennj** [comment]
Or should we just drop the OO stuff and
```tcl
proc matrixFrom {inputString} {
     return [lmap line [split $inputString \n] {split $line}]
}

proc row {matrix n} {
    return [lindex $matrix $n-1]
}

proc column {matrix n} {
    return [lmap row $matrix {lindex $row $n-1}]
}
```

**Comment by glennj** [comment]
@sshine, it's been a week: are you satisfied with the current situation?

**Pull request merged**
