### PR TITLE
redo configlet sync to rewrite tests.toml files

### PR DESCRIPTION
**Pull request by glennj**
This affects the tests.toml file for every exercise.

I have verified that the tests with `include = false` are correctly reflected in the new format.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
This seems to _Revert_ to the old format. Did you perhaps use an old configlet?

**Comment by glennj** [comment]
No, I fetched it first
```
$ bin/configlet --version
4.0.0-alpha.12
```
This is the current format: https://github.com/exercism/configlet/blob/d7dc31447315f5dbcb9d69afe60b4463a8f26417/src/sync/exercises.nim#L81

**Comment by SleeplessByte** [comment]
Right. So I expect each test to have a description key and an include key. The diff seems to do the opposite.

**Comment by glennj** [comment]
I read the configlet code the opposite way: the description is a comment (line 89) and the next line is `"UUID" = true|false`. This generates the "new" side of the diff. This matches the tests.toml format shown in the configlet README

I don't know what previous version of configlet generated the "old" style of toml here, with the "description" and "include" keys.

**Comment by SleeplessByte** [comment]
@glennj you're absolutely right. That code does exactly what you say you thought it does. Something's off here. It seems that `configlet` has NOT been updated with the latest canonical data syncer code. I'm pulling in @ErikSchierboom and @ee7 .

Pretty certain this is wrong. Here is the statement by Erik that shows the change:

image

Related PR: https://github.com/exercism/javascript/pull/1008

**Comment by ee7** [comment]
> It seems that `configlet` has NOT been updated with the latest canonical data syncer code.

A more accurate wording is "`configlet sync` has not been updated to support the new `tests.toml` spec". `canonical_data_syncer` doesn't exist anymore - it was replaced by `configlet sync`.

> **NOTE**: That PR says at the time of that PR, their code was not yet updated to support the new format.

Yes - this is still the current situation, sorry for the confusion. The issue to track it is https://github.com/exercism/configlet/issues/198.

This PR indeed reverts to the old format, and so isn't what we want. Actually, at some point there will be a mass-PR that removes all the `include = true` from the `tests.toml` files as they exist on `main`, so that most test cases look like

```
[1e22cceb-c5e4-4562-9afe-aef07ad1eaf4]
description = "basic"
```

**Comment by ErikSchierboom** [comment]
Yeah sorry about that. We are indeed in a situation where `configlet` currently doesn't output the right format. We will be working on that though.

**Comment by ee7** [comment]
> This matches the tests.toml format shown in the configlet README

Oops - it was outdated, sorry. Fixed.

**Comment by glennj** [comment]
Closing

**Comment by ee7** [comment]
As of the [latest configlet release](https://github.com/exercism/configlet/releases/tag/4.0.0-alpha.14), `configlet sync` now supports the new `tests.toml` format. Apologies that it took a while to add.

Please let me know if you find any problems with it.

**Pull request closed without merging**
