### PR TITLE
Create exercise: resistor-color-trio

### PR DESCRIPTION
**Pull request by glennj**
[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-trio/canonical-data.json)

### CODE REVIEW

**Comment by glennj** [comment]
I think the intention is to stick to integers. 1200 ohms VS 1.2 kiloohms, 3400 kiloohms, 5600 megaohms. I believe that's why I implemented

**Comment by glennj** [comment]
I mentored a solution on the bash trakc where the solution returned 1 kiloohms. I talked to him about loss of precision.

**Comment by sshine** [comment]
> I think the intention is to stick to integers. 1200 ohms VS 1.2 kiloohms

I hadn't even thought about that.

That's pretty neat.

I saw in my inbox that you mentioned having given feedback to this exercise and highlighted loss of precision as a critical point. If this exercise is eventually going to be mentored, I think it would help the mentor immensely that the unit test does something here.

How about we add optional / skip-by-default test cases that expect *either* `"1200 ohms"` *or* `"1.2 kiloohms"`? Then covering this part can be considered optional and can be interpreted either way depending on how people feel like.

**Comment by glennj** [comment]
That is a good idea. I'll submit a new PR soon.

**Pull request merged**
