### PR TITLE
add game-of-life

### PR DESCRIPTION
**Pull request by glennj**

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Comment by Steffan153** [comment]
The `./`s need removed from `config.json`; it doesn't work in the online editor right now.

**Comment by glennj** [comment]
@Steffan153 thanks for the report. Can you create an issue so the problem can be tracked.

**Comment by glennj** [comment]
I just have time for a quick note:

change in track config.json required here
```
  "files": {
    "solution": [
      "./%{kebab_slug}.tcl"
    ],
    "test": [
      "./%{kebab_slug}.test"
    ],
```
Affected exercises: game-of-life, state-of-tic-tac-toe.

**Comment by Steffan153** [comment]
An issue is just going to get auto-closed anyway, so here's a PR

https://github.com/exercism/tcl/pull/337

**Pull request merged**
