### PR TITLE
Acronym: create exercise

### PR DESCRIPTION
**Pull request by glennj**

### CODE REVIEW

**Comment by sshine** [comment]
I'm curious as to whether you regard it as idiomatic to not have an explicit `return` statement.

I didn't know that this was a property of Tcl, but since it is for Ruby and Perl, it doesn't surprise me.

In general I'd recommend against it. I recall Ruby learning material that encouraged this 10+ years ago, and I know of [`Perl::Critic::Policy::Subroutines::RequireFinalReturn`](https://metacpan.org/pod/Perl::Critic::Policy::Subroutines::RequireFinalReturn) in Perl.

**Comment by glennj** [comment]
I see this in the [wiki page on return](https://wiki.tcl-lang.org/page/return):
> `return` vs Falling off the End
> PYK 2016-09-15: Historically, `return` at the end of a procedure was slightly more performant than a final command that didn't explicitly return. This isn't the case in modern versions of Tcl, where procedures are byte-compiled.

Nevertheless, to encourage better style for students, I'll add a return.

**Comment by glennj** [comment]
I somehow messed up the commit history with making this change plus rebasing from master. the HEAD commit has 2 parents. Squash merge it shall be.

**Comment by glennj** [comment]
Wait, why are the raindrops files in this diff? Ugh, what a mess. I feel like recreating the branch. I've been using git for years but sometimes I'm a complete rookie with it.

**Comment by sshine** [comment]
Probably you did a `git checkout -b` from another feature branch because you were so blazingly fast at creating new exercises. :-D This happens once in a while. You could `git rebase -i` and squash all the commits that are relevant to the Acronym exercise (let's call this squashed commit `abc123`), `git branch -m port/acronym port/acronym-old`, `git checkout master`, `git checkout -b port/acronym`, `git cherry-pick abc123`, `git branch --set-upstream-to origin/port/acronym` and finally `git push -f`.

**Comment by glennj** [comment]
There we go. Thanks. I ended up not cherry picking because the contents are so simple.

**Pull request merged**
